/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexion.Conexion;
import dto.estudiante;
import dto.usuario;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author giovanny
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        login lg= new login();
        //System.out.println(lg.permisos);
        //System.out.println("visual principal: " + lg.us.getId());
        if(lg.permisos)
        {
                    carnet.setEnabled(true);
                    estado.setEnabled(true);
                    tipoS.setEnabled(true);
                    jButton4.setEnabled(true);
                    //us.setId(1);
        }else
        {
                    carnet.setEnabled(false);
                    estado.setEnabled(false);
                    tipoS.setEnabled(false);
                    //Boton de borrar se bloquea para los invitados
                    jButton4.setEnabled(false);
                    //us.setId(0);
        }
    }
    int proDocumento;
    usuario us= new usuario();
    
//    public void getDatos(usuario u)
//    {
////        u.getId();
////        u.getNombre();
////        u.getPermiso();
//        usuario usdatos= new usuario(u.getId(),u.getNombre(),u.getPermiso());
//        us=usdatos;
//        //System.out.println("lasm ierda de aca: " + us.getId()+ us.getNombre());
//        //System.out.println("lasm ierda de aca: " + u.getId());
//    }
    
    //login lg= new login();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton1 = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        doc = new javax.swing.JTextField();
        cod = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        carrera = new javax.swing.JTextField();
        semestre = new javax.swing.JTextField();
        facultad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        universidad = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        prom = new javax.swing.JTextField();
        sisben = new javax.swing.JTextField();
        graduado = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        carnet = new javax.swing.JComboBox<>();
        estado = new javax.swing.JComboBox<>();
        tipoS = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ingProgram = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JButton1.setText("Cargar");
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1ActionPerformed(evt);
            }
        });

        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Documento");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombres");

        jLabel4.setText("Correo");

        jLabel6.setText("Carrera");

        jLabel7.setText("Semestre");

        jLabel8.setText("Facultad");

        jLabel5.setText("Carnet");

        doc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docKeyTyped(evt);
            }
        });

        jLabel11.setText("Telefono");

        jLabel14.setText("Universidad");

        jLabel16.setText("Promedio/Año");

        jLabel9.setText("Estado");

        jLabel12.setText("Tipo/Subsidio");

        jLabel13.setText("Ciudad");

        jLabel15.setText("Inst/Graduado");

        jLabel10.setText("Sisben");

        sisben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisbenActionPerformed(evt);
            }
        });

        carnet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espera", "Aprobado", "Rechazado", "Retirado", "Graduado" }));

        tipoS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espera", "Completo", "Preferencial" }));

        jButton2.setText("Insertar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Año/IngresoPrograma");

        ingProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingProgramActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel18.setText("Documento");

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(doc, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(universidad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(prom, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(59, 59, 59))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tipoS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(13, 13, 13)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(graduado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(sisben, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(272, 272, 272))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327)
                        .addComponent(JButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(694, 694, 694))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(universidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel11))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel10)
                                .addComponent(jLabel15)
                                .addComponent(jLabel12)
                                .addComponent(jLabel17))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sisben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //MOSTRAR TODA LA BASE DE DATOS
    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1ActionPerformed
        // TODO add your handling code here:
        Conexion cn = new Conexion();
        cn.getConexion();
        //Sentencia sql para extraer todos los datos de la BD estudiantes
        ResultSet rs = cn.consultaGeneral("select documento,codigo,nombres,correo,universidad,carrera,semestre,facultad,carnet,telefono,promedio_año,estado,"
                + "tipo_subsidio,ciudad,institucion_graduado,sisben,año_ingreso_programa from estudiantes FETCH FIRST 20 ROWS ONLY");
        
        //MUESTRA LA TABLA
        try {
            DefaultTableModel dt = new DefaultTableModel();
            dt.addColumn("Dc");
            dt.addColumn("Cod");
            dt.addColumn("Nombres");
            dt.addColumn("Correo");
            dt.addColumn("Universidad");
            dt.addColumn("Carrera");
            dt.addColumn("Semestre");
            dt.addColumn("Facultad");
            dt.addColumn("Carnet");
            dt.addColumn("Telefono");
            dt.addColumn("Prom/año");
            dt.addColumn("Estado");
            dt.addColumn("T/Subs");
            dt.addColumn("Ciudad");
            dt.addColumn("Ins/Grad");
            dt.addColumn("Sisben");
            dt.addColumn("Ingr/Program");
//            
            while(rs.next())
            {
                //Obtiene los datos de la sentencia y los muestra en la tabla
                Object[] fila = new Object[17];
                fila[0] = rs.getInt(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                fila[7] = rs.getString(8);
                fila[8] = rs.getString(9);
                fila[9] = rs.getString(10);
                fila[10] = rs.getString(11);
                fila[11] = rs.getString(12);
                fila[12] = rs.getString(13);
                fila[13] = rs.getString(14);
                fila[14] = rs.getString(15);
                fila[15] = rs.getString(16);
                fila[16] = rs.getString(17);
                dt.addRow(fila);
            }
            rs.close();//cerrar el canal de comunicaciones con la BD
            this.tabla.setModel(dt);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos en la DB","Error",JOptionPane.ERROR_MESSAGE);
        }
        //System.out.println("visual puto estoy: " +us.getId()+ us.getNombre());
        //System.out.println("ojala q si de: " +us.getPermiso());
        
        
    }//GEN-LAST:event_JButton1ActionPerformed
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------
    //MOSTRAR UN REGISTRO ESPECIFICO
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Conexion cn = new Conexion();
        cn.getConexion();
        String id=null;
        if(campoBusqueda.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Campo busqueda vacio o ingreso letras","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            id=campoBusqueda.getText();
        }
        
        ResultSet rs = cn.consultaGeneral("select documento,codigo,nombres,correo,universidad,carrera,semestre,facultad,carnet,telefono,promedio_año,estado,"
                    + "tipo_subsidio,ciudad,institucion_graduado,sisben,año_ingreso_programa from estudiantes where documento=" + id);
       
        //MUESTRA LA TABLA
        try {
            //Sentencia sql para extraer todos los datos de la BD estudiantes
            DefaultTableModel dt = new DefaultTableModel();
            dt.addColumn("Dc");
            dt.addColumn("Cod");
            dt.addColumn("Nombres");
            dt.addColumn("Correo");            
            dt.addColumn("Universidad");
            dt.addColumn("Carrera");
            dt.addColumn("Semestre");
            dt.addColumn("Facultad");
            dt.addColumn("Carnet");
            dt.addColumn("Telefono");
            dt.addColumn("Prom/año");
            dt.addColumn("Estado");
            dt.addColumn("T/Subs");
            dt.addColumn("Ciudad");
            dt.addColumn("Ins/Grad");
            dt.addColumn("Sisben");
            dt.addColumn("Ingr/Program");
            
            while (rs.next()) {
                //Obtiene los datos de la sentencia y los muestra en la tabla
                Object[] fila = new Object[17];
                fila[0] = rs.getInt(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                fila[7] = rs.getString(8);
                fila[8] = rs.getString(9);
                fila[9] = rs.getString(10);
                fila[10] = rs.getString(11);
                fila[11] = rs.getString(12);
                fila[12] = rs.getString(13);
                fila[13] = rs.getString(14);
                fila[14] = rs.getString(15);
                fila[15] = rs.getString(16);
                fila[16] = rs.getString(17);
                dt.addRow(fila);
            }

            rs.close();//cerrar el canal de comunicaciones con la BD 
            this.tabla.setModel(dt);
        } catch (Exception e ) {
            //JOptionPane.showMessageDialog(null, "Error: No existe el registro EXCEEPTION");
            e.getMessage();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sisbenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisbenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisbenActionPerformed
//---------------------------------------------------------------------------------------------------------------------------------
//INSERTAR UN REGISTRO EN LA BD
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Conexion cn = new Conexion();
        cn.getConexion();
        if(doc.getText().equals(""))
        {
            
            JOptionPane.showMessageDialog(null, "Campo documento vacio","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        try {
            //Obtener datos de la vista
            estudiante est= new estudiante();
            
            est.setDocumento(Integer.parseInt(doc.getText()));
            est.setCodigo(cod.getText());
            est.setNombres(nom.getText());
            est.setCorreo(correo.getText());
            est.setCarrera(carrera.getText());
            est.setSemestre(semestre.getText());
            est.setFacultad(facultad.getText());
            est.setCarnet((String)carnet.getSelectedItem().toString());
            est.setTelefono(telefono.getText());
            est.setUniversidad(universidad.getText());
            est.setPromedio_año(prom.getText());
            est.setEstado((String)estado.getSelectedItem().toString());
            est.setTipo_subsidio((String)tipoS.getSelectedItem().toString());
            est.setCiudad(ciudad.getText());
            est.setInstitucion_graduado(graduado.getText());
            est.setSisben(sisben.getText());
            est.setAño_ingreso_programa(ingProgram.getText());
            est.setUsuarios_id(us.getId());
            est.setModifico(us.getNombre());
            //Inserta el dato
            cn.insertar(est);
            doc.setText("");
            cod.setText("");
            nom.setText("");
            correo.setText("");
            carrera.setText("");
            semestre.setText("");
            facultad.setText("");
            telefono.setText("");
            universidad.setText("");
            prom.setText("");
            ciudad.setText("");
            graduado.setText("");
            sisben.setText("");
            ingProgram.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            //JOptionPane.showMessageDialog(null,"Ya existe alguien con ese documento","Error",JOptionPane.ERROR_MESSAGE);
            //System.out.println("ya existe alguien con ese documento");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ingProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingProgramActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        //pone los datos de la tabla en los campos
        int posicion = tabla.getSelectedRow();
        proDocumento=((int)tabla.getValueAt(posicion, 0));
        doc.setText((tabla.getValueAt(posicion, 0).toString()));
        cod.setText((String) tabla.getValueAt(posicion, 1));
        nom.setText((String) tabla.getValueAt(posicion, 2));
        correo.setText((String) tabla.getValueAt(posicion, 3));
        universidad.setText((String) tabla.getValueAt(posicion, 4));
        carrera.setText((String) tabla.getValueAt(posicion, 5));
        semestre.setText((String) tabla.getValueAt(posicion, 6));
        facultad.setText((String) tabla.getValueAt(posicion, 7));
        carnet.setSelectedItem((String) tabla.getValueAt(posicion, 8));
        telefono.setText((String) tabla.getValueAt(posicion, 9));
        prom.setText((String) tabla.getValueAt(posicion, 10));
        estado.setSelectedItem((String) tabla.getValueAt(posicion, 11));
        tipoS.setSelectedItem((String) tabla.getValueAt(posicion, 12));
        ciudad.setText((String) tabla.getValueAt(posicion, 13));
        graduado.setText((String) tabla.getValueAt(posicion, 14));
        sisben.setText((String) tabla.getValueAt(posicion, 15));
        ingProgram.setText((String) tabla.getValueAt(posicion, 16));
    }//GEN-LAST:event_tablaMouseClicked
//---------------------------------------------------------------------------------------------------------------------------------
//ACTUALIZAR UN REGISTRO EN LA BD
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Conexion cn = new Conexion();
            cn.getConexion();
        //------------------------------------------------------
            int posicion = tabla.getSelectedRow();
            if(posicion == -1)
            {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun registro");
                return;
            }
            
            //Obtener datos de la vista
            estudiante est= new estudiante();
            est.setDocumento(Integer.parseInt(doc.getText()));
            est.setCodigo(cod.getText());
            est.setNombres(nom.getText());
            est.setCorreo(correo.getText());
            est.setCarrera(carrera.getText());
            est.setSemestre(semestre.getText());
            est.setFacultad(facultad.getText());
            est.setCarnet((String)carnet.getSelectedItem().toString());
            est.setTelefono(telefono.getText());
            est.setUniversidad(universidad.getText());
            est.setPromedio_año(prom.getText());
            est.setEstado((String)estado.getSelectedItem().toString());
            est.setTipo_subsidio((String)tipoS.getSelectedItem().toString());
            est.setCiudad(ciudad.getText());
            est.setInstitucion_graduado(graduado.getText());
            est.setSisben(sisben.getText());
            est.setAño_ingreso_programa(ingProgram.getText());
            est.setUsuarios_id(us.getId());
            est.setModifico(us.getNombre());
            //Inserta el dato
            // cn.actualizar(est,proDocumento);
            cn.actualizar(est,proDocumento);
    }//GEN-LAST:event_jButton3ActionPerformed
//---------------------------------------------------------------------------------------------------------------------------------------------
//Eliminar de la BD
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
         //No ha seleccionado alguna fila
            int posicion = tabla.getSelectedRow();
            if(posicion == -1)
            {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun registro");
                return;
            }
            //Ha seleccionado alguna fila
            if(posicion != -1)
            {
                //Opcion que escogio en el mensaje
                int opciones=JOptionPane.showConfirmDialog(null, "Seguro que desea borrar a: " + tabla.getValueAt(posicion, 2), "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                System.out.println(opciones);
                //Presiono Si
                if(opciones == 0)
                {
                    Conexion cn = new Conexion();
                    cn.getConexion();
                    int idestudiante=(int)tabla.getValueAt(posicion, 0);
                    estudiante est= new estudiante(idestudiante);
                    try {
                        cn.borrar(est);
                        JOptionPane.showMessageDialog(null, "Error: Se borro correctamente");
                        
                    } catch (SQLException ex) {
                        //Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Error: No se pudo borrar");
                    }
                    
                }
                else
                {
                    
                }
            }
    }//GEN-LAST:event_jButton4ActionPerformed
//SOLO DEJAR INGRESAR NUMEROS
    private void docKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docKeyTyped
        char c = evt.getKeyChar();
        
        if(c < '0' || c>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_docKeyTyped

    private void campoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyTyped
        char b = evt.getKeyChar();
        
        if(b < '0' || b>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_campoBusquedaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton1;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JComboBox<String> carnet;
    private javax.swing.JTextField carrera;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField doc;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField facultad;
    private javax.swing.JTextField graduado;
    private javax.swing.JTextField ingProgram;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prom;
    private javax.swing.JTextField semestre;
    private javax.swing.JTextField sisben;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipoS;
    private javax.swing.JTextField universidad;
    // End of variables declaration//GEN-END:variables
}
